/**
 * TimelineExport Component
 *
 * Renders a print-friendly, shareable timeline of thread events.
 * Designed for export as PDF or forwarding as a standalone document.
 *
 * Key principles:
 * - No interactive elements (no buttons, links, or forms)
 * - No UI chrome or marketing language
 * - Neutral, factual presentation
 * - High contrast for printing
 * - Understandable by someone unfamiliar with Vigil
 */

import React from 'react';
import { TimelineEvent } from './timeline';

export interface TimelineExportData {
  threadSubject: string;
  watcherName: string;
  generatedAt: number;
  events: TimelineEvent[];
}

export interface TimelineExportProps {
  data: TimelineExportData;
}

function formatTimestamp(timestamp: number): string {
  const date = new Date(timestamp);
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
    timeZoneName: 'short',
  });
}

function formatDate(timestamp: number): string {
  const date = new Date(timestamp);
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  });
}

export function TimelineExport({ data }: TimelineExportProps) {
  const { threadSubject, watcherName, generatedAt, events } = data;

  // Sort events chronologically (oldest first)
  const sortedEvents = [...events].sort((a, b) => a.timestamp - b.timestamp);

  return (
    <div className="timeline-export bg-white text-gray-900 p-8 max-w-3xl mx-auto font-sans">
      {/* Header */}
      <header className="mb-8 border-b border-gray-300 pb-6">
        <h1 className="text-2xl font-semibold text-gray-900 mb-2">
          {threadSubject}
        </h1>
        <div className="text-sm text-gray-600 space-y-1">
          <p>Watcher: {watcherName}</p>
          <p>Generated: {formatDate(generatedAt)}</p>
        </div>
      </header>

      {/* Timeline */}
      <section className="mb-8">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-700 mb-4">
          Event Timeline
        </h2>

        {sortedEvents.length === 0 ? (
          <p className="text-gray-500 italic">No events recorded</p>
        ) : (
          <ol className="space-y-4" role="list">
            {sortedEvents.map((event) => (
              <li
                key={event.id}
                className="border-l-2 border-gray-200 pl-4 py-1"
              >
                <div className="flex items-baseline justify-between gap-4">
                  <span className="text-sm font-medium text-gray-800">
                    {event.type}
                  </span>
                  <time
                    className="text-xs text-gray-500 tabular-nums whitespace-nowrap"
                    dateTime={new Date(event.timestamp).toISOString()}
                  >
                    {formatTimestamp(event.timestamp)}
                  </time>
                </div>

                {event.description && (
                  <p className="text-sm text-gray-600 mt-1">
                    {event.description}
                  </p>
                )}

                {event.source && (
                  <p className="text-xs text-gray-500 mt-0.5">
                    Source: {event.source}
                  </p>
                )}
              </li>
            ))}
          </ol>
        )}
      </section>

      {/* Footer */}
      <footer className="pt-6 border-t border-gray-200 text-xs text-gray-500">
        <p>Generated by Vigil - Communication Timeline</p>
      </footer>
    </div>
  );
}

export default TimelineExport;
