'use client';

import Link from 'next/link';
import { PublicHeader, Footer } from '@/components/layout';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-surface-page">
      <PublicHeader />
      <main className="pt-28 pb-20">
        <div className="max-w-3xl mx-auto px-6">
          <p className="text-sm font-medium text-vigil-700 uppercase tracking-wider mb-3">Data & Privacy</p>
          <h1 className="text-4xl md:text-5xl font-display font-semibold text-gray-900 tracking-tight mb-5">
            Your data. Your control.
          </h1>
          <p className="text-xl text-gray-600 leading-relaxed mb-12">
            Vigil is built on a simple principle: we process your email without keeping it. 
            This page explains exactly what we store, what we discard, how we protect what remains, 
            and what rights you have over your data.
          </p>

          <div className="prose">
            <h2>What Vigil Never Has Access To</h2>
            <ul>
              <li><strong>Your inbox.</strong> Vigil never connects to Gmail, Outlook, or any email provider. No OAuth tokens, no API connections, no inbox permissions. You forward emails to us. We only see what you choose to send.</li>
              <li><strong>Email bodies.</strong> The content of every email is processed in memory and discarded immediately after analysis. Email bodies are never written to disk, never stored in a database, never logged. We cannot retrieve the original content of any email.</li>
              <li><strong>Attachments.</strong> We do not process, store, or read email attachments.</li>
            </ul>

            <h2>What We Store</h2>
            <p>We store only what the agent needs to track your obligations over time:</p>
            <ul>
              <li><strong>Email metadata</strong> — sender address, recipient address, subject line, timestamps (when it was sent, when it was delivered, when Vigil received it). This is the envelope, not the letter.</li>
              <li><strong>Agent analysis</strong> — a one-sentence summary, the sender&apos;s intent, urgency level, and extracted entities (names, dates, amounts). This is generated by AI, not raw email content.</li>
              <li><strong>Thread state</strong> — conversation groupings, status (active/watching/resolved/ignored), participant list, email count.</li>
              <li><strong>Agent memories</strong> — atomic facts the agent chose to remember: deadlines, amounts, commitments. Each memory has an importance level and can be viewed, edited, or deleted by you.</li>
              <li><strong>Action log</strong> — every decision the agent made: what tool it used, why, what model processed it, how much it cost, how long it took.</li>
              <li><strong>Account data</strong> — email address, hashed password, billing information (handled by Stripe).</li>
            </ul>

            <h2>What You Can See and Do</h2>
            <p>Every piece of data Vigil stores about you is visible in your dashboard:</p>
            <ul>
              <li><strong>Inbox tab</strong> — every email that was processed, with the agent&apos;s analysis</li>
              <li><strong>Activity tab</strong> — every action the agent took, with its reasoning</li>
              <li><strong>Memory tab</strong> — every fact the agent remembers, editable and deletable by you</li>
              <li><strong>Settings</strong> — your agent&apos;s prompt, tools, reactivity, model, and channels</li>
              <li><strong>Developer page</strong> — your API keys with usage tracking</li>
              <li><strong>Billing page</strong> — your current usage and cost, with Stripe portal access</li>
            </ul>
            <p>You have full visibility into everything Vigil knows about you. There is no hidden data.</p>

            <h2>Data Protection Measures</h2>

            <h3>Encryption</h3>
            <ul>
              <li>All data in transit is encrypted via TLS 1.2+ (HTTPS enforced with HSTS)</li>
              <li>Passwords are hashed with industry-standard one-way hashing (never stored in plain text)</li>
              <li>API keys are hashed before storage — we cannot see your full key after creation</li>
            </ul>

            <h3>Access Control</h3>
            <ul>
              <li>Authentication via JWT tokens with short expiry</li>
              <li>API key authentication for programmatic access</li>
              <li>Rate limiting on all endpoints (auth, API, email ingestion)</li>
              <li>CORS restricted to vigil.run domains only</li>
            </ul>

            <h3>Infrastructure Security</h3>
            <ul>
              <li>Firewall: only ports 22 (SSH, key-only), 80, and 443 are open</li>
              <li>SSH: password authentication disabled, key-based access only</li>
              <li>SSL certificates auto-renewed via Let&apos;s Encrypt</li>
              <li>Security headers: HSTS, X-Frame-Options DENY, Content-Type-Options nosniff, XSS protection</li>
              <li>Webhook payloads signed with HMAC-SHA256 for verification</li>
            </ul>

            <h3>Email Body Discarding</h3>
            <p>
              When an email arrives, it is parsed in memory. The agent reads the body, generates its analysis, 
              and the body is then discarded. A SHA-256 hash of the body is stored as a proof-of-receipt 
              (cryptographic proof that we received a specific email, without storing the content). 
              This hash cannot be reversed to recover the original email.
            </p>

            <h2>Third-Party Services</h2>
            <ul>
              <li><strong>Stripe</strong> — handles payment processing. We never see your full card number. Stripe&apos;s privacy policy applies to payment data.</li>
              <li><strong>OpenAI / Anthropic / Google</strong> — email content is sent to the selected AI model provider for analysis. Their data processing terms apply. Email content is not stored by these providers for model training when using API access.</li>
              <li><strong>Resend</strong> — delivers alert emails. Receives only the alert content (not the original email body).</li>
              <li><strong>Cloudflare</strong> — routes incoming email via MX records. Processes raw MIME data in transit.</li>
            </ul>

            <h2>Data Retention</h2>
            <ul>
              <li><strong>Email metadata and analysis</strong> — retained until you delete the thread or your account</li>
              <li><strong>Agent memories</strong> — retained until you delete them, the agent marks them obsolete, or you delete your account</li>
              <li><strong>Action logs</strong> — retained for the lifetime of the watcher</li>
              <li><strong>Account data</strong> — retained until you delete your account</li>
            </ul>

            <h2>Your Rights</h2>
            <ul>
              <li><strong>Access</strong> — all your data is visible in your dashboard at all times</li>
              <li><strong>Edit</strong> — you can edit agent memories and watcher configuration</li>
              <li><strong>Delete</strong> — you can delete individual threads, memories, watchers, or your entire account</li>
              <li><strong>Export</strong> — you can access all your data via the API using your API key</li>
              <li><strong>Portability</strong> — your data is accessible via standard REST API in JSON format</li>
            </ul>

            <h2>Account Deletion</h2>
            <p>
              When you delete your account, all associated data is permanently removed: 
              watchers, threads, email metadata, memories, action logs, API keys, and billing records. 
              This action is irreversible. Stripe retains payment history per their own retention policy.
            </p>

            <h2>Changes to This Policy</h2>
            <p>
              If we change how we handle your data, we will notify you via the email address on your account 
              before the changes take effect. Continued use of Vigil after notification constitutes acceptance 
              of the updated policy.
            </p>

            <h2>Contact</h2>
            <p>
              Questions about your data or privacy? Email <a href="mailto:privacy@vigil.run">privacy@vigil.run</a>.
            </p>

            <p className="text-sm text-gray-400 mt-8">Last updated: March 14, 2026</p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
