import React from 'react';
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { TimelineExport, TimelineExportData } from '@/components/timeline-export';

const mockData: TimelineExportData = {
  threadSubject: 'Contract Review Request',
  watcherName: 'Legal Department',
  generatedAt: 1704153600000, // 2024-01-02 00:00:00 UTC
  events: [
    {
      id: 'evt-1',
      type: 'EMAIL_RECEIVED',
      timestamp: 1704067200000,
      description: 'Message received',
      source: 'sender@example.com',
    },
    {
      id: 'evt-2',
      type: 'THREAD_OPENED',
      timestamp: 1704067260000,
      description: 'Thread opened',
    },
    {
      id: 'evt-3',
      type: 'EMAIL_RECEIVED',
      timestamp: 1704153600000,
      description: 'Message received',
      source: 'reply@example.com',
    },
  ],
};

describe('TimelineExport Component', () => {
  it('renders thread subject as header', () => {
    render(<TimelineExport data={mockData} />);

    expect(screen.getByText('Contract Review Request')).toBeInTheDocument();
  });

  it('displays all events without truncation', () => {
    render(<TimelineExport data={mockData} />);

    const items = screen.getAllByRole('listitem');
    expect(items).toHaveLength(3);
  });

  it('shows watcher name in header', () => {
    render(<TimelineExport data={mockData} />);

    expect(screen.getByText(/Legal Department/)).toBeInTheDocument();
  });

  it('includes generation timestamp', () => {
    render(<TimelineExport data={mockData} />);

    // Should have generation timestamp in header
    expect(screen.getByText(/Generated:/)).toBeInTheDocument();
  });

  it('contains no interactive elements', () => {
    render(<TimelineExport data={mockData} />);

    expect(screen.queryAllByRole('button')).toHaveLength(0);
    expect(screen.queryAllByRole('link')).toHaveLength(0);
  });

  it('includes minimal footer identifying Vigil', () => {
    render(<TimelineExport data={mockData} />);

    expect(screen.getByText(/Generated by Vigil/)).toBeInTheDocument();
  });

  it('uses neutral language without judgment', () => {
    render(<TimelineExport data={mockData} />);

    const content = document.body.textContent || '';
    expect(content).not.toMatch(/overdue|late|missed|urgent|critical|warning|failed/i);
  });

  it('displays events in chronological order', () => {
    render(<TimelineExport data={mockData} />);

    const items = screen.getAllByRole('listitem');
    // Events should be ordered chronologically (earliest first)
    expect(items[0]).toHaveTextContent('EMAIL_RECEIVED');
    expect(items[1]).toHaveTextContent('THREAD_OPENED');
  });

  it('formats timestamps consistently', () => {
    render(<TimelineExport data={mockData} />);

    // All events should have timestamp elements
    const timeElements = document.querySelectorAll('time');
    expect(timeElements.length).toBeGreaterThan(0);
  });
});

describe('TimelineExport - Print Friendly', () => {
  it('renders without colored backgrounds', () => {
    const { container } = render(<TimelineExport data={mockData} />);

    // Should not have background colors that waste ink
    const element = container.firstChild as HTMLElement;
    expect(element.className).not.toContain('bg-blue');
    expect(element.className).not.toContain('bg-red');
    expect(element.className).not.toContain('bg-green');
  });

  it('uses high-contrast text for readability', () => {
    const { container } = render(<TimelineExport data={mockData} />);

    // Main content should use dark text on light background
    expect(container.textContent).toBeTruthy();
  });
});
