export default function SecurityPage() {
  return (
    <div className="prose">
      <p className="text-sm font-medium text-vigil-700 uppercase tracking-wider mb-3">Documentation</p>
      <h1>Security & Privacy</h1>
      <p>Vigil's privacy model is architectural, not policy-based. The system physically cannot access your inbox.</p>

      <h2>No inbox access</h2>
      <p>Vigil never uses OAuth, never connects to Gmail or Outlook APIs, never requests inbox permissions. You forward emails using standard email forwarding rules. Vigil sees only what you choose to forward.</p>

      <h2>Email bodies are discarded</h2>
      <p>When an email arrives, the agent processes the body text in memory. After analysis, the body is discarded. Only a SHA-256 hash is stored as proof of receipt. There is no way to retrieve the original email content from Vigil.</p>

      <h2>What we store</h2>
      <ul>
        <li>Email metadata (from, to, subject, timestamps)</li>
        <li>Agent analysis (summary, intent, urgency — generated by AI, not raw content)</li>
        <li>Thread state and memories</li>
        <li>Action log with reasoning</li>
        <li>Account credentials (hashed passwords, JWT tokens)</li>
      </ul>

      <h2>Authentication</h2>
      <ul>
        <li>Passwords hashed with bcrypt</li>
        <li>JWT access tokens (1 hour expiry) + refresh tokens (24 hours)</li>
        <li>Rate limiting on auth endpoints (10 requests per 15 minutes)</li>
        <li>CORS restricted to vigil.run origins</li>
      </ul>

      <h2>Webhook security</h2>
      <p>All webhook payloads are signed with HMAC-SHA256 using your watcher's signing secret. Verify the <code>X-Vigil-Signature</code> header to confirm authenticity.</p>
    </div>
  );
}
